#!/usr/bin/ksh
#
# Note, if ksh is not available, you can use
# another shell like zsh
#
##################################################
##################################################
# This script will compile all executable programs
# that are required by extra package for FMTOMO
##################################################
##################################################
#
# YOU MUST SPECIFY A FORTRAN 90 COMPILER!!!!
# Compiler options can be included at this stage
# if deemed necessary by the user.
#
##################################################
F90=gfortran
##################################################
#
# Enter the directory called "source" and compile
# all programs.
#
##################################################
cd source
$F90 -o frvpvs frvpvs.f90
$F90 -o gridloc gridloc.f90
$F90 -o gridlocj gridlocj.f90
$F90 -o jointimes jointimes.f90
$F90 -o mkvpvs mkvpvs.f90
$F90 -o obsdatai obsdatai.f90
$F90 -o vpvsinv vpvsinv.f90
$F90 -o vpvsresids vpvsresids.f90
$F90 -o grid3dgi grid3dgi.f90
$F90 -o gmtslicei gmtslicei.f90
$F90 -o synthdatai synthdatai.f90
##################################################
#
# Move all executables to  directory ../bin
#
##################################################
mv frvpvs gridloc gridlocj ../bin
mv jointimes mkvpvs obsdatai ../bin
mv vpvsinv vpvsresids grid3dgi ../bin
mv gmtslicei synthdatai ../bin
cp cp_script tomo3di tomo3dj tomo3dps ../bin
cd ..
echo " "
echo "Compilation complete"
