#!/usr/bin/bash
##################################################
##################################################
# This script will compile all executable programs
# that are required by GUI LET FMTOMO
##################################################
##################################################
#
# YOU MUST SPECIFY A FORTRAN 90 COMPILER!!!!
# Compiler options can be included at this stage
# if deemed necessary by the user.
#
##################################################
F90=gfortran
##################################################
#
# Enter the directory called "source" and compile
# all programs.
#
##################################################
cd source
$F90 -o frvpvs frvpvs.f90
$F90 -o gridloc gridloc.f90
$F90 -o gridlocj gridlocj.f90
$F90 -o jointimes jointimes.f90
$F90 -o mkvpvs mkvpvs.f90
$F90 -o obsdatai obsdatai.f90
$F90 -o vpvsinv vpvsinv.f90
$F90 -o vpvsresids vpvsresids.f90
$F90 -o grid3dgi grid3dgi.f90
$F90 -o gmtslicei gmtslicei.f90
$F90 -o synthdatai synthdatai.f90
$F90 -o arraygen arraygen.f90
$F90 -o frechgen frechgen.f90
$F90 -o gmtslice gmtslice.f90
$F90 -o grid3dg grid3dg.f90
$F90 -o invert3d invert3d.f90
$F90 -o moddata moddata.f90
$F90 -o obsdata obsdata.f90
$F90 -o residuals residuals.f90
$F90 -o synthdata synthdata.f90
$F90 -o scorrect scorrect.f90
$F90 -o mprop mprop.f90
##################################################
#
# Move all executables to  directory ../bin
#
##################################################
mv frvpvs gridloc gridlocj ../bin
mv jointimes mkvpvs obsdatai ../bin
mv vpvsinv vpvsresids grid3dgi ../bin
mv gmtslicei synthdatai ../bin
cp cp_script tomo3di tomo3dj tomo3dps ../bin
mv arraygen frechgen gmtslice ../bin
mv grid3dg invert3d moddata ../bin
mv obsdata residuals synthdata ../bin
mv scorrect ../bin
mv mprop ../bin
##################################################
#
# Enter subdirectory "fmcode", compile
# "fm3d", and move it to ../bin directory. Copy
# input file to ../sources/inputfiles
#
##################################################
cd ../fmcode
make fm3d
make clean
mv fm3d ../bin
cp mode_set.in ../source/inputfiles
##################################################
#
# Enter subdirectory "aktimes" and compile programs
# for generating traveltime tables
#
##################################################
cd aktimes
make all
make clean
remodl
setbrn
##################################################
#
# Copy output binary traveltime tables to
# ../../source/inputfiles
#
##################################################
cp ak135.tbl ak135.hed ../../source/inputfiles
##################################################
cd ..
echo " "
echo "Compilation complete"
